# Generated by Django 5.2 on 2025-04-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('status_long', models.CharField(max_length=50)),
                ('status_short', models.CharField(max_length=10)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('goals_home', models.IntegerField(blank=True, null=True)),
                ('goals_away', models.IntegerField(blank=True, null=True)),
                ('score_ht_home', models.IntegerField(blank=True, null=True)),
                ('score_ht_away', models.IntegerField(blank=True, null=True)),
                ('score_ft_home', models.IntegerField(blank=True, null=True)),
                ('score_ft_away', models.IntegerField(blank=True, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.season')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.venue')),
            ],
        ),
    ]
